name: Bug Report
description: File a bug report.
title: "[👾]: "
labels: ["👾 Bug"]
assignees:
  - sungsoos
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Write down what happened! ex: "RPC didnt show up."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide a list of steps to reproduce the issue.
      placeholder: "Write down the steps to reproduce the issue! ex: \"1. Open game. 2. Open Discord. 3. RPC doesn't show up.\""
    validations:
      required: true

  - type: textarea
    id: various-info
    attributes:
      label: Additional Information
      description: Please provide any additional information that might be helpful in diagnosing the issue.
      placeholder: "Write down any additional information! ex: \"I was playing on a Mac with latest version of deltarune with korean patch installed.\""
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: false
      options:
        - Windows
        - macOS
        - Linux

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. It's not required, but it can help diagnose the issue faster.
      render: shell
    validations:
      required: false

  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
